name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 자동 실행
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Ie-ight/travel-maker-frontend.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes into develop
        run: |
          git checkout develop
          git merge upstream/develop --allow-unrelated-histories || true

      - name: Push changes to forked repository
        run: git push origin develop
